In [50]:
!pip install plotly

Collecting plotly
  Using cached plotly-7.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: narwhals>=1.15.1 in .\.conda\envs\notebook-env\Lib\site-packages (from plotly) (2.26.0)
Requirement already satisfied: packaging in .\.conda\envs\notebook-env\Lib\site-packages (from plotly) (26.3)
Using cached plotly-7.1.0-py3-none-any.whl (9.7 MB)
Installing collected packages: plotly
Successfully installed plotly-7.1.0

In [51]:
import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st

In [52]:
df= pd.read_csv(r'C:\Users\Maison\Downloads\Sales_transactions_2022_2025\Sales_transactions_2022_2025.csv')
df

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18040,T02006253,O0106253,C03487,Ella Adams,32.0,Male,New Customer,2022-01-11,10:44:18,Online,...,Completed,Express,2.0,No,NaN,Emma Carter,MOM15,5.0,52.0,2022
18041,T02005688,O0102844,C00418,Jack Jones,32.0,Male,Returning Customer,2023-10-09,08:26:43,Retail Store,...,Processing,Standard,3.0,No,NaN,Emma Carter,SAVE10,4.0,107.0,2023
18042,T02011672,O0111672,C03311,Oscar Williams,37.0,Male,Corporate,2025-04-02,17:45:09,Online,...,Completed,Standard,6.0,No,NaN,Sophia Brown,SAVE10,2.0,58.0,2025
18043,T02013094,O0113094,C01590,Benjamin Moore,21.0,Female,New Customer,2022-06-08,15:03:38,Online,...,Completed,Standard,7.0,No,NaN,Noah Wilson,BLACKFRIDAY25,3.0,32.0,2022
18044,T02011617,O0111617,C01479,Lucas Allen,55.0,Male,Consumer,2025-06-30,19:01:38,Retail Store,...,Completed,Pickup,0.0,No,NaN,Grace Harris,NaN,5.0,73.0,2025

In [53]:
df.duplicated().sum()

np.int64(45)

In [54]:
df.drop_duplicates(inplace=True)

In [55]:
df.duplicated().sum()

np.int64(0)

In [56]:
df.isna().sum()

Transaction_ID              0
Order_ID                    0
Customer_ID                 0
Customer_Name             108
Customer_Age              216
Customer_Gender           162
Customer_Segment            0
Order_Date                  0
Order_Time                  0
Sales_Channel               0
Store_ID                    0
Store_Name                  0
Country                     0
Region                      0
City                        0
Product_ID                  0
Product_Name              144
Product_Category            0
Product_Subcategory         0
Quantity                    0
Unit_Price                  0
Discount_Percentage         0
Sales_Amount                0
Cost_Amount                 0
Profit                      0
Payment_Method            144
Order_Status                0
Shipping_Method             0
Delivery_Days             162
Return_Flag                 0
Return_Reason           16127
Sales_Representative        0
Promotion_Code           9712
Customer_Rating          3430
Inventory_Level           198
Order_Year                  0
dtype: int64

In [57]:
round(df.isna().mean()*100,2)

Transaction_ID           0.00
Order_ID                 0.00
Customer_ID              0.00
Customer_Name            0.60
Customer_Age             1.20
Customer_Gender          0.90
Customer_Segment         0.00
Order_Date               0.00
Order_Time               0.00
Sales_Channel            0.00
Store_ID                 0.00
Store_Name               0.00
Country                  0.00
Region                   0.00
City                     0.00
Product_ID               0.00
Product_Name             0.80
Product_Category         0.00
Product_Subcategory      0.00
Quantity                 0.00
Unit_Price               0.00
Discount_Percentage      0.00
Sales_Amount             0.00
Cost_Amount              0.00
Profit                   0.00
Payment_Method           0.80
Order_Status             0.00
Shipping_Method          0.00
Delivery_Days            0.90
Return_Flag              0.00
Return_Reason           89.59
Sales_Representative     0.00
Promotion_Code          53.96
Customer_Rating         19.06
Inventory_Level          1.10
Order_Year               0.00
dtype: float64

In [58]:
pd.crosstab(df['Return_Flag'], df['Return_Reason'], dropna=False)

Return_Reason,Changed Mind,Damaged,Defective,Late Delivery,Other,Wrong Item,NaN
Return_Flag,,,,,,,
No,0,0,0,0,0,0,16127
Yes,300,312,302,331,311,317,0

In [59]:
df['Return_Reason'] = df['Return_Reason'].fillna('Not Returned')

In [60]:
df['Return_Reason'].isnull().sum()

np.int64(0)

In [61]:
df['Promotion_Code'] = df['Promotion_Code'].fillna('No Promotion')

In [62]:
df['Promotion_Code'].isnull().sum()

np.int64(0)

In [63]:
df = df.loc[:, ~df.columns.duplicated(keep='first')]

In [64]:
round(df.isna().mean()*100,2)

Transaction_ID           0.00
Order_ID                 0.00
Customer_ID              0.00
Customer_Name            0.60
Customer_Age             1.20
Customer_Gender          0.90
Customer_Segment         0.00
Order_Date               0.00
Order_Time               0.00
Sales_Channel            0.00
Store_ID                 0.00
Store_Name               0.00
Country                  0.00
Region                   0.00
City                     0.00
Product_ID               0.00
Product_Name             0.80
Product_Category         0.00
Product_Subcategory      0.00
Quantity                 0.00
Unit_Price               0.00
Discount_Percentage      0.00
Sales_Amount             0.00
Cost_Amount              0.00
Profit                   0.00
Payment_Method           0.80
Order_Status             0.00
Shipping_Method          0.00
Delivery_Days            0.90
Return_Flag              0.00
Return_Reason            0.00
Sales_Representative     0.00
Promotion_Code           0.00
Customer_Rating         19.06
Inventory_Level          1.10
Order_Year               0.00
dtype: float64

In [65]:
df['Customer_Age'].median()

np.float64(39.0)

In [66]:
categorical_cols = [
    'Customer_Name',
    'Customer_Gender',
    'Product_Name',
    'Payment_Method'
]

df[categorical_cols] = df[categorical_cols].fillna('Unknown')

In [67]:
df[['Delivery_Days', 'Inventory_Level']].describe()

       Delivery_Days  Inventory_Level
count   17838.000000     17802.000000
mean        2.262361        70.246714
std         2.321260        22.040191
min         0.000000         0.000000
25%         0.000000        55.000000
50%         1.000000        70.000000
75%         4.000000        85.000000
max        10.000000       157.000000

In [68]:
df[df['Delivery_Days'].isnull()]['Order_Status'].value_counts(dropna=False)

Order_Status
Completed     106
Shipped        18
Returned       17
Processing     14
Cancelled       6
completed       1
Name: count, dtype: int64

In [69]:
print("Total rows:", len(df))
print("Missing Delivery_Days:", df['Delivery_Days'].isna().sum())
print("Non-missing Delivery_Days:", df['Delivery_Days'].count())

Total rows: 18000
Missing Delivery_Days: 162
Non-missing Delivery_Days: 17838

In [70]:
df.loc[df['Delivery_Days'].isna(), 'Order_Status'].value_counts()

Order_Status
Completed     106
Shipped        18
Returned       17
Processing     14
Cancelled       6
completed       1
Name: count, dtype: int64

In [71]:
df['Order_Status'] = df['Order_Status'].str.strip().str.title()

In [72]:
df.loc[
    df['Delivery_Days'].isna() & (df['Order_Status'] == 'Completed')
].head()

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
208,T02010784,O0105392,C05310,Theo Allen,24.0,Female,Corporate,2024-06-20,13:02:25,B2B Portal,...,Completed,Standard,NaN,No,Not Returned,Emma Carter,No Promotion,NaN,89.0,2024
274,T02011502,O0105751,C03532,Samuel Taylor,24.0,Female,Corporate,2023-12-01,17:19:51,Retail Store,...,Completed,Pickup,NaN,No,Not Returned,Amelia Jackson,SAVE10,5.0,65.0,2023
790,T02012763,O0112763,C02406,Sophia Lewis,32.0,Female,Returning Customer,2023-11-06,13:25:22,Retail Store,...,Completed,Pickup,NaN,No,Not Returned,James Anderson,No Promotion,3.0,81.0,2023
793,T02003425,O0103425,C02277,Sophie Williams,47.0,Female,Consumer,2025-11-29,12:22:03,Retail Store,...,Completed,Pickup,NaN,No,Not Returned,Ella Lewis,No Promotion,5.0,64.0,2025
894,T02003196,O0103196,C04748,Arthur White,60.0,Male,Consumer,2022-07-28,09:16:41,Online,...,Completed,Pickup,NaN,No,Not Returned,Mia Taylor,VALENTINE20,4.0,58.0,2022

In [73]:
missing_completed = df[
    df['Delivery_Days'].isnull() &
    (df['Order_Status'] == 'Completed')
]

In [74]:
missing_completed['Shipping_Method'].value_counts(dropna=False)

Shipping_Method
Standard    48
Pickup      44
Express      8
Next Day     7
Name: count, dtype: int64

In [75]:
pd.crosstab(
    [df['Order_Status'], df['Shipping_Method']],
    df['Delivery_Days'].isna(),
    dropna=False
)

Delivery_Days                 False  True
Order_Status Shipping_Method
Cancelled    Express            110      0
             Next Day            50      0
             Pickup             339      3
             Standard           388      3
Completed    Express           1525      8
             Next Day           602      7
             Pickup            4416     44
             Standard          4886     48
Processing   Express            192      1
             Next Day            60      1
             Pickup             550      4
             Standard           604      8
Returned     Express            206      3
             Next Day            90      0
             Pickup             587      5
             Standard           697      9
Shipped      Express            331      1
             Next Day           139      0
             Pickup             980     11
             Standard          1086      6

In [76]:
df.groupby('Shipping_Method')['Delivery_Days'].median()

Shipping_Method
Express     1.0
Next Day    1.0
Pickup      0.0
Standard    5.0
Name: Delivery_Days, dtype: float64

In [77]:
df.groupby ('Shipping_Method')['Delivery_Days'].transform(lambda x : x.fillna (x.median()))

0        4.0
1        6.0
2        4.0
3        2.0
4        2.0
        ...
18040    2.0
18041    3.0
18042    6.0
18043    7.0
18044    0.0
Name: Delivery_Days, Length: 18000, dtype: float64

In [78]:
pd.crosstab(
    [df['Order_Status'], df['Shipping_Method']],
    df['Delivery_Days'].isna()
)[True]

Order_Status  Shipping_Method
Cancelled     Express             0
              Next Day            0
              Pickup              3
              Standard            3
Completed     Express             8
              Next Day            7
              Pickup             44
              Standard           48
Processing    Express             1
              Next Day            1
              Pickup              4
              Standard            8
Returned      Express             3
              Next Day            0
              Pickup              5
              Standard            9
Shipped       Express             1
              Next Day            0
              Pickup             11
              Standard            6
Name: True, dtype: int64

In [79]:
df.loc[
    df['Delivery_Days'].isna(),
    ['Order_ID', 'Order_Status', 'Shipping_Method', 'Order_Date', 'Delivery_Days']
].head(10)

      Order_ID Order_Status Shipping_Method  Order_Date  Delivery_Days
208   O0105392    Completed        Standard  2024-06-20            NaN
274   O0105751    Completed          Pickup  2023-12-01            NaN
441   O0107149      Shipped         Express  2023-02-28            NaN
667   O0100442      Shipped          Pickup  2023-03-07            NaN
689   O0104588   Processing          Pickup  2025-04-24            NaN
790   O0112763    Completed          Pickup  2023-11-06            NaN
793   O0103425    Completed          Pickup  2025-11-29            NaN
863   O0104811     Returned        Standard  2023-03-08            NaN
894   O0103196    Completed          Pickup  2022-07-28            NaN
1060  O0103469    Completed          Pickup  2023-09-28            NaN

In [80]:
df.isna().sum()

Transaction_ID             0
Order_ID                   0
Customer_ID                0
Customer_Name              0
Customer_Age             216
Customer_Gender            0
Customer_Segment           0
Order_Date                 0
Order_Time                 0
Sales_Channel              0
Store_ID                   0
Store_Name                 0
Country                    0
Region                     0
City                       0
Product_ID                 0
Product_Name               0
Product_Category           0
Product_Subcategory        0
Quantity                   0
Unit_Price                 0
Discount_Percentage        0
Sales_Amount               0
Cost_Amount                0
Profit                     0
Payment_Method             0
Order_Status               0
Shipping_Method            0
Delivery_Days            162
Return_Flag                0
Return_Reason              0
Sales_Representative       0
Promotion_Code             0
Customer_Rating         3430
Inventory_Level          198
Order_Year                 0
dtype: int64

In [81]:
print("Median age:", df['Customer_Age'].median())

Median age: 39.0

In [82]:
df['Customer_Age'] = df['Customer_Age'].fillna(
    df['Customer_Age'].median()
)

In [83]:
print("Missing ages after filling:", df['Customer_Age'].isna().sum())

Missing ages after filling: 0

In [84]:
df['Inventory_Level'] = df['Inventory_Level'].fillna(
    df['Inventory_Level'].median()
)

In [85]:
print("Missing Inventory Level after filling:", df['Inventory_Level'].isna().sum())

Missing Inventory Level after filling: 0

In [86]:
df.isna().sum()

Transaction_ID             0
Order_ID                   0
Customer_ID                0
Customer_Name              0
Customer_Age               0
Customer_Gender            0
Customer_Segment           0
Order_Date                 0
Order_Time                 0
Sales_Channel              0
Store_ID                   0
Store_Name                 0
Country                    0
Region                     0
City                       0
Product_ID                 0
Product_Name               0
Product_Category           0
Product_Subcategory        0
Quantity                   0
Unit_Price                 0
Discount_Percentage        0
Sales_Amount               0
Cost_Amount                0
Profit                     0
Payment_Method             0
Order_Status               0
Shipping_Method            0
Delivery_Days            162
Return_Flag                0
Return_Reason              0
Sales_Representative       0
Promotion_Code             0
Customer_Rating         3430
Inventory_Level            0
Order_Year                 0
dtype: int64

In [87]:
df['Order_Time'].head()

0    11:30:55
1    17:06:29
2    08:22:11
3    14:32:43
4    14:55:16
Name: Order_Time, dtype: str

In [88]:
df['Order_Date'] = pd.to_datetime(
    df['Order_Date'], errors='coerce'
)

df['Order_Time'] = pd.to_datetime(
    df['Order_Time'], format='%H:%M:%S', errors='coerce'
).dt.time

In [89]:
print(df[['Order_Date', 'Order_Time']].dtypes)

df[['Order_Date', 'Order_Time']].head()

Order_Date    datetime64[us]
Order_Time            object
dtype: object

  Order_Date Order_Time
0 2022-10-06   11:30:55
1 2024-06-03   17:06:29
2 2024-12-19   08:22:11
3 2025-10-05   14:32:43
4 2022-09-13   14:55:16

In [90]:
for col in ['Customer_Gender', 'Sales_Channel',
            'Order_Status', 'Payment_Method']:
    print(f'\n{col}:')
    print(df[col].value_counts(dropna=False))

Customer_Gender:
Customer_Gender
Female        8720
Male          8418
Non-binary     541
Unknown        162
male            77
FEMALE          74
Non Binary       8
Name: count, dtype: int64

Sales_Channel:
Sales_Channel
Online          8195
Retail Store    6221
B2B Portal      2124
Phone Order     1460
Name: count, dtype: int64

Order_Status:
Order_Status
Completed     11536
Shipped        2554
Returned       1597
Processing     1420
Cancelled       893
Name: count, dtype: int64

Payment_Method:
Payment_Method
Credit Card      6725
Debit Card       3888
PayPal           2793
Bank Transfer    2135
Apple Pay        1087
Cash             1038
Unknown           144
credit card        79
DebitCard          66
paypal             23
Bank transfer      22
Name: count, dtype: int64

In [91]:
df['Customer_Gender'] = (
    df['Customer_Gender']
    .str.strip()
    .replace({
        'male': 'Male',
        'FEMALE': 'Female',
        'Non Binary': 'Non-binary'
    })
)

In [92]:
df['Payment_Method'] = (
    df['Payment_Method']
    .str.strip()
    .replace({
        'credit card': 'Credit Card',
        'DebitCard': 'Debit Card',
        'paypal': 'PayPal',
        'Bank transfer': 'Bank Transfer'
    })
)

In [93]:
for col in ['Customer_Gender', 'Sales_Channel',
            'Order_Status', 'Payment_Method']:
    print(f'\n{col}:')
    print(df[col].value_counts(dropna=False))

Customer_Gender:
Customer_Gender
Female        8794
Male          8495
Non-binary     549
Unknown        162
Name: count, dtype: int64

Sales_Channel:
Sales_Channel
Online          8195
Retail Store    6221
B2B Portal      2124
Phone Order     1460
Name: count, dtype: int64

Order_Status:
Order_Status
Completed     11536
Shipped        2554
Returned       1597
Processing     1420
Cancelled       893
Name: count, dtype: int64

Payment_Method:
Payment_Method
Credit Card      6804
Debit Card       3954
PayPal           2816
Bank Transfer    2157
Apple Pay        1087
Cash             1038
Unknown           144
Name: count, dtype: int64

In [94]:
df[['Customer_Age', 'Quantity', 'Unit_Price',
    'Sales_Amount', 'Cost_Amount', 'Profit',
    'Discount_Percentage', 'Delivery_Days']].describe().T

,count,mean,std,min,25%,50%,75%,max
Customer_Age,18000.0,38.917944,10.658819,4.00,32.0000,39.000,46.0000,112.00
Quantity,18000.0,2.126500,1.784690,-3.00,1.0000,2.000,3.0000,11.00
Unit_Price,18000.0,232.775236,294.249699,21.39,52.9575,99.845,285.7825,1425.09
Sales_Amount,18000.0,457.449478,857.097154,16.68,78.5250,168.845,472.7425,14303.07
Cost_Amount,18000.0,366.132677,706.335962,12.17,56.1050,122.315,376.1450,10791.00
Profit,18000.0,91.413300,167.856392,-299.31,19.4900,40.190,93.3000,3512.08
Discount_Percentage,18000.0,6.254722,6.879860,0.00,0.0000,5.000,10.0000,110.00
Delivery_Days,17838.0,2.262361,2.321260,0.00,0.0000,1.000,4.0000,10.00

In [95]:
df.loc[
    (df['Customer_Age'] < 10) | (df['Customer_Age'] > 100),
    ['Customer_ID', 'Customer_Age']
].head(10)

      Customer_ID  Customer_Age
1851       C02947         112.0
17270      C00821           4.0

In [96]:
df.loc[
    (df['Customer_Age'] < 10) | (df['Customer_Age'] > 100)
]

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
1851,T02003795,O0101897,C02947,Alexander Williams,112.0,Female,Consumer,2025-06-30,12:39:52,Retail Store,...,Cancelled,Standard,2.0,No,Not Returned,Amelia Jackson,BLACKFRIDAY25,5.0,57.0,2025
17270,T02010919,O0110919,C00821,Sophie Wright,4.0,Male,Consumer,2022-11-01,20:05:10,Online,...,Completed,Express,1.0,No,Not Returned,Grace Harris,HOLIDAY20,3.0,63.0,2022

In [97]:
df = df.loc[~df['Customer_Age'].isin([4, 112])].reset_index(drop=True)

In [98]:
df['Customer_Age'].isin([4, 112]).sum()

np.int64(0)

In [99]:
df.loc[
    df['Quantity'] < 0,
    ['Transaction_ID', 'Order_ID', 'Quantity',
     'Order_Status', 'Return_Flag', 'Sales_Amount', 'Profit']
].head(10)

,Transaction_ID,Order_ID,Quantity,Order_Status,Return_Flag,Sales_Amount,Profit
3983,T02006553,O0103276,-2,Shipped,No,273.09,17.16
7479,T02011209,O0111209,-1,Processing,No,460.31,89.12
12129,T02004207,O0104207,-3,Completed,No,868.21,140.35

In [100]:
df.loc[
    df['Quantity'] < 0,
    ['Transaction_ID', 'Order_ID', 'Product_Name',
     'Quantity', 'Unit_Price', 'Discount_Percentage',
     'Sales_Amount', 'Cost_Amount', 'Profit',
     'Order_Status', 'Return_Flag', 'Return_Reason']
]

,Transaction_ID,Order_ID,Product_Name,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Order_Status,Return_Flag,Return_Reason
3983,T02006553,O0103276,Air Purifier,-2,341.36,20.0,273.09,255.93,17.16,Shipped,No,Not Returned
7479,T02011209,O0111209,Backup Drive 2TB,-1,127.86,10.0,460.31,371.19,89.12,Processing,No,Not Returned
12129,T02004207,O0104207,Meeting Table,-3,913.91,5.0,868.21,727.86,140.35,Completed,No,Not Returned

In [101]:
df = df.loc[df['Quantity'] > 0].reset_index(drop=True)

In [102]:
print("Rows with zero or negative quantities:",
      (df['Quantity'] <= 0).sum())
print("Dataset shape:", df.shape)

Rows with zero or negative quantities: 0
Dataset shape: (17990, 36)

In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17990 entries, 0 to 17989
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Transaction_ID        17990 non-null  str
 1   Order_ID              17990 non-null  str
 2   Customer_ID           17990 non-null  str
 3   Customer_Name         17990 non-null  str
 4   Customer_Age          17990 non-null  float64
 5   Customer_Gender       17990 non-null  str
 6   Customer_Segment      17990 non-null  str
 7   Order_Date            17990 non-null  datetime64[us]
 8   Order_Time            17990 non-null  object
 9   Sales_Channel         17990 non-null  str
 10  Store_ID              17990 non-null  str
 11  Store_Name            17990 non-null  str
 12  Country               17990 non-null  str
 13  Region                17990 non-null  str
 14  City                  17990 non-null  str
 15  Product_ID            17990 non-null  str
 16  Product_Name          17990 non-null  str
 17  Product_Category      17990 non-null  str
 18  Product_Subcategory   17990 non-null  str
 19  Quantity              17990 non-null  int64
 20  Unit_Price            17990 non-null  float64
 21  Discount_Percentage   17990 non-null  float64
 22  Sales_Amount          17990 non-null  float64
 23  Cost_Amount           17990 non-null  float64
 24  Profit                17990 non-null  float64
 25  Payment_Method        17990 non-null  str
 26  Order_Status          17990 non-null  str
 27  Shipping_Method       17990 non-null  str
 28  Delivery_Days         17828 non-null  float64
 29  Return_Flag           17990 non-null  str
 30  Return_Reason         17990 non-null  str
 31  Sales_Representative  17990 non-null  str
 32  Promotion_Code        17990 non-null  str
 33  Customer_Rating       14560 non-null  float64
 34  Inventory_Level       17990 non-null  float64
 35  Order_Year            17990 non-null  int64
dtypes: datetime64[us](1), float64(9), int64(2), object(1), str(23)
memory usage: 8.6+ MB

In [104]:
df['Customer_Age'] = df['Customer_Age'].astype('Int64')

In [105]:
df.dtypes

Transaction_ID                     str
Order_ID                           str
Customer_ID                        str
Customer_Name                      str
Customer_Age                     Int64
Customer_Gender                    str
Customer_Segment                   str
Order_Date              datetime64[us]
Order_Time                      object
Sales_Channel                      str
Store_ID                           str
Store_Name                         str
Country                            str
Region                             str
City                               str
Product_ID                         str
Product_Name                       str
Product_Category                   str
Product_Subcategory                str
Quantity                         int64
Unit_Price                     float64
Discount_Percentage            float64
Sales_Amount                   float64
Cost_Amount                    float64
Profit                         float64
Payment_Method                     str
Order_Status                       str
Shipping_Method                    str
Delivery_Days                  float64
Return_Flag                        str
Return_Reason                      str
Sales_Representative               str
Promotion_Code                     str
Customer_Rating                float64
Inventory_Level                float64
Order_Year                       int64
dtype: object

In [106]:
print("Invalid ages:", ((df['Customer_Age'] < 0) |
                        (df['Customer_Age'] > 120)).sum())

print("Non-positive quantities:", (df['Quantity'] <= 0).sum())

print("Negative unit prices:", (df['Unit_Price'] < 0).sum())

Invalid ages: 0
Non-positive quantities: 0
Negative unit prices: 0

In [107]:
print(df['Discount_Percentage'].describe())
print(sorted(df['Discount_Percentage'].unique()))

count    17990.000000
mean         6.252918
std          6.880245
min          0.000000
25%          0.000000
50%          5.000000
75%         10.000000
max        110.000000
Name: Discount_Percentage, dtype: float64
[np.float64(0.0), np.float64(5.0), np.float64(10.0), np.float64(15.0), np.float64(20.0), np.float64(25.0), np.float64(30.0), np.float64(45.0), np.float64(60.0), np.float64(110.0)]

In [108]:
print("Discounts above 100%:",
      (df['Discount_Percentage'] > 100).sum())

print("Discounts below 0%:",
      (df['Discount_Percentage'] < 0).sum())

Discounts above 100%: 1
Discounts below 0%: 0

In [109]:
df = df.loc[
    df['Discount_Percentage'].between(0, 100)
].reset_index(drop=True)

In [110]:
print(df['Discount_Percentage'].max())
print((df['Discount_Percentage'] > 100).sum())

60.0
0

In [111]:
(df['Cost_Amount'] <= 0).sum()

np.int64(0)

In [112]:
(df['Profit'] != (df['Sales_Amount'] - df['Cost_Amount']).round(2)).sum()

np.int64(4544)

In [113]:
df.loc[
    (df['Profit'] !=
     (df['Sales_Amount'] - df['Cost_Amount']).round(2)),
    ['Transaction_ID', 'Sales_Amount',
     'Cost_Amount', 'Profit']
].head(10)

   Transaction_ID  Sales_Amount  Cost_Amount  Profit
11      T02005146         59.69        38.59   21.09
13      T02004775         65.60        46.74   18.87
18      T02010845        204.01       165.10   38.90
22      T02012915        135.14        97.10   38.05
23      T02006472         46.17        37.13    9.05
32      T02012120        141.39       106.07   35.31
34      T02011968        109.13        86.14   22.98
36      T02006475        809.85       696.60  113.24
37      T02000920        617.31       486.95  130.37
40      T02003015         94.08        71.05   23.02

In [114]:
df['Calculated_Profit'] = (
    df['Sales_Amount'] - df['Cost_Amount']
).round(2)

df['Profit_Difference'] = (
    df['Profit'] - df['Calculated_Profit']
).round(2)

df['Profit_Difference'].describe()

count    17989.000000
mean         0.096558
std          7.357997
min       -321.570000
25%          0.000000
50%          0.000000
75%          0.000000
max        301.690000
Name: Profit_Difference, dtype: float64

In [115]:
df.reset_index(drop=True, inplace=True)

In [116]:
df.shape

(17989, 38)

In [117]:
cat_cols = df.select_dtypes(include=['str', 'object']).columns

In [118]:
cat_cols

Index(['Transaction_ID', 'Order_ID', 'Customer_ID', 'Customer_Name',
       'Customer_Gender', 'Customer_Segment', 'Order_Time', 'Sales_Channel',
       'Store_ID', 'Store_Name', 'Country', 'Region', 'City', 'Product_ID',
       'Product_Name', 'Product_Category', 'Product_Subcategory',
       'Payment_Method', 'Order_Status', 'Shipping_Method', 'Return_Flag',
       'Return_Reason', 'Sales_Representative', 'Promotion_Code'],
      dtype='str')

In [119]:
for col in cat_cols :
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-'*50)

Transaction_ID
17989
<ArrowStringArray>
['T02016694', 'T02016374', 'T02004099', 'T02010280', 'T02012685', 'T02003704',
 'T02016542', 'T02013460', 'T02001029', 'T02001635',
 ...
 'T02005105', 'T02004187', 'T02007434', 'T02015694', 'T02014571', 'T02006253',
 'T02005688', 'T02011672', 'T02013094', 'T02011617']
Length: 17989, dtype: str
--------------------------------------------------
Order_ID
14533
<ArrowStringArray>
['O0116694', 'O0108187', 'O0104099', 'O0110280', 'O0112685', 'O0101852',
 'O0116542', 'O0113460', 'O0101029', 'O0101635',
 ...
 'O0105985', 'O0105105', 'O0104187', 'O0107434', 'O0107847', 'O0114571',
 'O0106253', 'O0111672', 'O0113094', 'O0111617']
Length: 14533, dtype: str
--------------------------------------------------
Customer_ID
4882
<ArrowStringArray>
['C01482', 'C01591', 'C04140', 'C03663', 'C02749', 'C00959', 'C02232',
 'C00719', 'C01511', 'C04415',
 ...
 'C04458', 'C00754', 'C00210', 'C01919', 'C00366', 'C05043', 'C03194',
 'C00443', 'C01531', 'C03311']
Length: 4882, dtype: str
--------------------------------------------------
Customer_Name
1180
<ArrowStringArray>
[    'Sophia Smith',      'Hannah King',      'Emma Wilson',
     'Daniel Clark',       'Mia Miller',     'Evelyn Adams',
    'Olivia Walker',      'Emily Moore',   'Freya Williams',
       'Lily Allen',
 ...
     'Arthur Davis',     'Samuel Brown',        'Maya Hall',
        'Ella King',  'Alexander Lewis',     'James Wright',
       'Nora Young',  'William Jackson',   'Grace Anderson',
 'Charlotte Martin']
Length: 1180, dtype: str
--------------------------------------------------
Customer_Gender
4
<ArrowStringArray>
['Male', 'Female', 'Non-binary', 'Unknown']
Length: 4, dtype: str
--------------------------------------------------
Customer_Segment
6
<ArrowStringArray>
[          'Consumer',          'Corporate', 'Returning Customer',
       'New Customer',     'Small Business',            'Premium']
Length: 6, dtype: str
--------------------------------------------------
Order_Time
15192
[datetime.time(11, 30, 55) datetime.time(17, 6, 29)
 datetime.time(8, 22, 11) ... datetime.time(10, 44, 18)
 datetime.time(8, 26, 43) datetime.time(17, 45, 9)]
--------------------------------------------------
Sales_Channel
4
<ArrowStringArray>
['Online', 'B2B Portal', 'Retail Store', 'Phone Order']
Length: 4, dtype: str
--------------------------------------------------
Store_ID
12
<ArrowStringArray>
[ 'LA-01', 'SYD-01', 'PAR-01', 'NYC-01', 'CHI-01', 'TOR-01', 'VAN-01',
 'AUS-01', 'LON-01', 'COL-01', 'MAN-01', 'MUC-01']
Length: 12, dtype: str
--------------------------------------------------
Store_Name
12
<ArrowStringArray>
['Los Angeles Downtown',           'Sydney CBD',        'Paris Central',
     'New York Central',         'Chicago Loop',      'Toronto Central',
       'Vancouver West',      'Austin Business',          'London City',
     'Cologne Business',     'Manchester North',       'Munich Zentrum']
Length: 12, dtype: str
--------------------------------------------------
Country
6
<ArrowStringArray>
['United States', 'Australia', 'France', 'Canada', 'United Kingdom',
 'Germany']
Length: 6, dtype: str
--------------------------------------------------
Region
14
<ArrowStringArray>
[                  'West',        'New South Wales',          'Île-de-France',
              'Northeast',                'Midwest',                'Ontario',
       'British Columbia',                  'South',                'England',
 'North Rhine-Westphalia',                'Bavaria',             'North East',
       'British columbia',                    'NRW']
Length: 14, dtype: str
--------------------------------------------------
City
15
<ArrowStringArray>
['LOS ANGELES',      'Sydney',       'Paris',    'New York',     'Chicago',
     'Toronto',   'Vancouver',      'Austin',      'London',     'Cologne',
 'Los Angeles',  'Manchester',  ' New York ',      'Munich',      'munich']
Length: 15, dtype: str
--------------------------------------------------
Product_ID
28
<ArrowStringArray>
['P026', 'P005', 'P017', 'P008', 'P013', 'P012', 'P027', 'P003', 'P006',
 'P002', 'P024', 'P009', 'P004', 'P028', 'P022', 'P018', 'P025', 'P015',
 'P016', 'P020', 'P001', 'P019', 'P023', 'P014', 'P007', 'P021', 'P011',
 'P010']
Length: 28, dtype: str
--------------------------------------------------
Product_Name
29
<ArrowStringArray>
[          'Webcam HD',     'Office Keyboard',      'Copy Paper Box',
     'SmartDock USB-C',           'Desk Lamp',       'Ergo Footrest',
     'Security Camera',   'EdgeTab 11 Tablet',     'Precision Mouse',
   'ProBook 16 Laptop',            'Desk Fan',    'Office Chair Pro',
   'Vision 27 Monitor',    'Backup Drive 2TB',        'Air Purifier',
        'Premium Pens',       'USB Power Hub',        'Printer Plus',
         'Laser Toner',    'Presentation Kit',  'AeroBook 14 Laptop',
       'Notebook Pack',     'Portable Heater',      'Filing Cabinet',
 'NoiseCancel Headset',      'Coffee Machine',       'Meeting Table',
       'Standing Desk',             'Unknown']
Length: 29, dtype: str
--------------------------------------------------
Product_Category
7
<ArrowStringArray>
[    'Electronics', 'Office Supplies',       'Furniture',      'Appliances',
       'FURNITURE',     'electronics', 'Office supplies']
Length: 7, dtype: str
--------------------------------------------------
Product_Subcategory
17
<ArrowStringArray>
[         'Cameras',      'Accessories',            'Paper',
         'Lighting', 'Office Furniture',          'Tablets',
          'Laptops',          'Climate',         'Monitors',
          'Storage',      'Home Office',          'Writing',
         'Printers',      'Consumables',     'Presentation',
            'Audio',          'Kitchen']
Length: 17, dtype: str
--------------------------------------------------
Payment_Method
7
<ArrowStringArray>
[  'Credit Card',    'Debit Card',        'PayPal',     'Apple Pay',
          'Cash', 'Bank Transfer',       'Unknown']
Length: 7, dtype: str
--------------------------------------------------
Order_Status
5
<ArrowStringArray>
['Completed', 'Shipped', 'Returned', 'Processing', 'Cancelled']
Length: 5, dtype: str
--------------------------------------------------
Shipping_Method
4
<ArrowStringArray>
['Standard', 'Next Day', 'Express', 'Pickup']
Length: 4, dtype: str
--------------------------------------------------
Return_Flag
2
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------
Return_Reason
7
<ArrowStringArray>
[ 'Not Returned',       'Damaged',  'Changed Mind',         'Other',
     'Defective', 'Late Delivery',    'Wrong Item']
Length: 7, dtype: str
--------------------------------------------------
Sales_Representative
16
<ArrowStringArray>
[  'James Anderson',       'Ella Lewis',       'Liam Davis',
     'Grace Harris',     'Sophia Brown',      'Noah Wilson',
    'Olivia Martin',     'David Walker',       'Mia Taylor',
   'Amelia Jackson',      'Henry White',    'Daniel Miller',
 'Charlotte Thomas',      'Lucas Moore',      'Emma Carter',
    'Michael Clark']
Length: 16, dtype: str
--------------------------------------------------
Promotion_Code
11
<ArrowStringArray>
[       'SAVE10',  'No Promotion',     'HOLIDAY20', 'BLACKFRIDAY25',
         'MOM15',   'HALLOWEEN15',     'BACK2WORK',   'VALENTINE20',
      'SUMMER10',         'CORP5',      'SPRING15']
Length: 11, dtype: str
--------------------------------------------------

In [120]:
df['Region'] = df['Region'].str.strip().replace({
    'British columbia': 'British Columbia',
    'NRW': 'North Rhine-Westphalia',
    'North East': 'Northeast'
})

In [121]:
df['City'] = df['City'].str.strip().str.title()

In [122]:
df['Product_Category'] = (
    df['Product_Category'].str.strip().str.title()
)

In [123]:
for col in ['Region', 'City', 'Product_Category']:
    print(col)
    print(df[col].unique())
    print('-' * 40)

Region
<ArrowStringArray>
[                  'West',        'New South Wales',          'Île-de-France',
              'Northeast',                'Midwest',                'Ontario',
       'British Columbia',                  'South',                'England',
 'North Rhine-Westphalia',                'Bavaria']
Length: 11, dtype: str
----------------------------------------
City
<ArrowStringArray>
['Los Angeles',      'Sydney',       'Paris',    'New York',     'Chicago',
     'Toronto',   'Vancouver',      'Austin',      'London',     'Cologne',
  'Manchester',      'Munich']
Length: 12, dtype: str
----------------------------------------
Product_Category
<ArrowStringArray>
['Electronics', 'Office Supplies', 'Furniture', 'Appliances']
Length: 4, dtype: str
----------------------------------------

In [124]:
df['Calculated_Profit'] = df['Sales_Amount'] - df['Cost_Amount']

df['Profit_Mismatch'] = np.isclose(
    df['Profit'],
    df['Calculated_Profit'],
    atol=0.01
)

print("Profit mismatches:", df['Profit_Mismatch'].sum())

Profit mismatches: 17879

In [125]:
df.loc[
    df['Profit_Mismatch'],
    ['Sales_Amount', 'Cost_Amount',
     'Profit', 'Calculated_Profit']
].head(10)

   Sales_Amount  Cost_Amount  Profit  Calculated_Profit
0        162.05       115.61   46.44              46.44
1        300.13       237.00   63.13              63.13
2         74.66        73.17    1.49               1.49
3       1078.46       897.91  180.55             180.55
4        237.03       164.95   72.08              72.08
5         75.96        50.09   25.87              25.87
6        118.64       102.11   16.53              16.53
7        159.81       118.34   41.47              41.47
8        956.28       805.86  150.42             150.42
9        168.81       124.22   44.59              44.59

In [126]:
df['Calculated_Profit'] = (
    df['Sales_Amount'] - df['Cost_Amount']
)

df['Profit_Mismatch'] = ~np.isclose(
    df['Profit'],
    df['Calculated_Profit'],
    atol=0.01
)

print("Profit mismatches:", df['Profit_Mismatch'].sum())

Profit mismatches: 110

In [127]:
df.loc[
    df['Profit_Mismatch'],
    ['Transaction_ID', 'Sales_Amount', 'Cost_Amount',
     'Profit', 'Calculated_Profit']
].head(10)

     Transaction_ID  Sales_Amount  Cost_Amount  Profit  Calculated_Profit
274       T02011502        234.83       213.11   92.44              21.72
442       T02012573        114.16        78.59   28.66              35.57
802       T02002177        223.92       193.15   69.78              30.77
817       T02013340       1289.96      1107.31  222.30             182.65
962       T02009106        135.72        84.99  124.85              50.73
1134      T02009758         42.28        29.37   12.08              12.91
1264      T02005711        546.27       436.33  126.43             109.94
1552      T02007133        181.06       148.44  121.77              32.62
1664      T02002984        680.61       502.21  174.64             178.40
1855      T02000839        225.45       188.78  296.92              36.67

In [128]:
df.loc[
    df['Profit_Mismatch'],
    ['Profit', 'Calculated_Profit']
].assign(
    Difference=lambda x:
        (x['Profit'] - x['Calculated_Profit']).round(2)
)['Difference'].describe()

count    110.000000
mean      15.793818
std       93.190193
min     -321.570000
25%       -6.687500
50%        6.335000
75%       44.775000
max      301.690000
Name: Difference, dtype: float64

In [129]:
df.drop(
    columns=['Calculated_Profit', 'Profit_Mismatch'],
    inplace=True
)

In [130]:
df.columns.tolist()

['Transaction_ID',
 'Order_ID',
 'Customer_ID',
 'Customer_Name',
 'Customer_Age',
 'Customer_Gender',
 'Customer_Segment',
 'Order_Date',
 'Order_Time',
 'Sales_Channel',
 'Store_ID',
 'Store_Name',
 'Country',
 'Region',
 'City',
 'Product_ID',
 'Product_Name',
 'Product_Category',
 'Product_Subcategory',
 'Quantity',
 'Unit_Price',
 'Discount_Percentage',
 'Sales_Amount',
 'Cost_Amount',
 'Profit',
 'Payment_Method',
 'Order_Status',
 'Shipping_Method',
 'Delivery_Days',
 'Return_Flag',
 'Return_Reason',
 'Sales_Representative',
 'Promotion_Code',
 'Customer_Rating',
 'Inventory_Level',
 'Order_Year',
 'Profit_Difference']

In [131]:
print("Python is working")

Python is working

In [132]:
df.shape

(17989, 37)

In [133]:
df.columns.tolist()

['Transaction_ID',
 'Order_ID',
 'Customer_ID',
 'Customer_Name',
 'Customer_Age',
 'Customer_Gender',
 'Customer_Segment',
 'Order_Date',
 'Order_Time',
 'Sales_Channel',
 'Store_ID',
 'Store_Name',
 'Country',
 'Region',
 'City',
 'Product_ID',
 'Product_Name',
 'Product_Category',
 'Product_Subcategory',
 'Quantity',
 'Unit_Price',
 'Discount_Percentage',
 'Sales_Amount',
 'Cost_Amount',
 'Profit',
 'Payment_Method',
 'Order_Status',
 'Shipping_Method',
 'Delivery_Days',
 'Return_Flag',
 'Return_Reason',
 'Sales_Representative',
 'Promotion_Code',
 'Customer_Rating',
 'Inventory_Level',
 'Order_Year',
 'Profit_Difference']

In [134]:
df.shape

(17989, 37)

In [135]:
print("Shape:", df.shape)
print("Number of columns:", len(df.columns))
print("Duplicate rows:", df.duplicated().sum())

print("\nColumns:")
for i, col in enumerate(df.columns, start=1):
    print(i, col)

Shape: (17989, 37)
Number of columns: 37
Duplicate rows: 0

Columns:
1 Transaction_ID
2 Order_ID
3 Customer_ID
4 Customer_Name
5 Customer_Age
6 Customer_Gender
7 Customer_Segment
8 Order_Date
9 Order_Time
10 Sales_Channel
11 Store_ID
12 Store_Name
13 Country
14 Region
15 City
16 Product_ID
17 Product_Name
18 Product_Category
19 Product_Subcategory
20 Quantity
21 Unit_Price
22 Discount_Percentage
23 Sales_Amount
24 Cost_Amount
25 Profit
26 Payment_Method
27 Order_Status
28 Shipping_Method
29 Delivery_Days
30 Return_Flag
31 Return_Reason
32 Sales_Representative
33 Promotion_Code
34 Customer_Rating
35 Inventory_Level
36 Order_Year
37 Profit_Difference

In [136]:
print("Missing values:", df.isna().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Current shape:", df.shape)

Missing values: 3592
Duplicate rows: 0
Current shape: (17989, 37)

In [137]:
df.isna().sum()

Transaction_ID             0
Order_ID                   0
Customer_ID                0
Customer_Name              0
Customer_Age               0
Customer_Gender            0
Customer_Segment           0
Order_Date                 0
Order_Time                 0
Sales_Channel              0
Store_ID                   0
Store_Name                 0
Country                    0
Region                     0
City                       0
Product_ID                 0
Product_Name               0
Product_Category           0
Product_Subcategory        0
Quantity                   0
Unit_Price                 0
Discount_Percentage        0
Sales_Amount               0
Cost_Amount                0
Profit                     0
Payment_Method             0
Order_Status               0
Shipping_Method            0
Delivery_Days            162
Return_Flag                0
Return_Reason              0
Sales_Representative       0
Promotion_Code             0
Customer_Rating         3430
Inventory_Level            0
Order_Year                 0
Profit_Difference          0
dtype: int64

In [138]:
round(df.isna().mean()*100,2)

Transaction_ID           0.00
Order_ID                 0.00
Customer_ID              0.00
Customer_Name            0.00
Customer_Age             0.00
Customer_Gender          0.00
Customer_Segment         0.00
Order_Date               0.00
Order_Time               0.00
Sales_Channel            0.00
Store_ID                 0.00
Store_Name               0.00
Country                  0.00
Region                   0.00
City                     0.00
Product_ID               0.00
Product_Name             0.00
Product_Category         0.00
Product_Subcategory      0.00
Quantity                 0.00
Unit_Price               0.00
Discount_Percentage      0.00
Sales_Amount             0.00
Cost_Amount              0.00
Profit                   0.00
Payment_Method           0.00
Order_Status             0.00
Shipping_Method          0.00
Delivery_Days            0.90
Return_Flag              0.00
Return_Reason            0.00
Sales_Representative     0.00
Promotion_Code           0.00
Customer_Rating         19.07
Inventory_Level          0.00
Order_Year               0.00
Profit_Difference        0.00
dtype: float64

In [139]:
df['Order_Year'].value_counts(dropna=False)

Order_Year
2025    4965
2023    4598
2024    4343
2022    4083
Name: count, dtype: int64

In [140]:
df.drop(columns=['Profit_Difference'], inplace=True)

In [141]:
df.isna().sum()

Transaction_ID             0
Order_ID                   0
Customer_ID                0
Customer_Name              0
Customer_Age               0
Customer_Gender            0
Customer_Segment           0
Order_Date                 0
Order_Time                 0
Sales_Channel              0
Store_ID                   0
Store_Name                 0
Country                    0
Region                     0
City                       0
Product_ID                 0
Product_Name               0
Product_Category           0
Product_Subcategory        0
Quantity                   0
Unit_Price                 0
Discount_Percentage        0
Sales_Amount               0
Cost_Amount                0
Profit                     0
Payment_Method             0
Order_Status               0
Shipping_Method            0
Delivery_Days            162
Return_Flag                0
Return_Reason              0
Sales_Representative       0
Promotion_Code             0
Customer_Rating         3430
Inventory_Level            0
Order_Year                 0
dtype: int64

In [143]:
pd.crosstab(df['Order_Status'], df['Delivery_Days'], dropna=False)

Delivery_Days,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,NaN
Order_Status,,,,,,,,,,,,
Cancelled,339,102,57,80,109,96,65,28,8,2,0,6
Completed,4415,1320,779,1071,1358,1250,759,362,86,22,1,107
Processing,550,147,102,139,161,151,103,36,14,2,0,14
Returned,587,196,112,133,190,186,111,50,12,2,0,17
Shipped,980,311,146,234,314,264,185,77,20,3,0,18

In [145]:
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Duplicate rows:", df.duplicated().sum())
print("Missing delivery days:", df['Delivery_Days'].isna().sum())

Rows: 17989
Columns: 36
Duplicate rows: 0
Missing delivery days: 162

In [199]:
px.bar(df['Order_Year'].value_counts().reset_index(),x='Order_Year',y='count',title='Orders by Year',color_discrete_sequence=['lightblue']).update_xaxes(dtick=1,tickmode='linear').show()

In [200]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [207]:
monthly_sales = (
    df.groupby(df['Order_Date'].dt.to_period('M'))['Sales_Amount']
    .sum()
    .reset_index()
)

monthly_sales['Order_Date'] = monthly_sales['Order_Date'].dt.to_timestamp()

In [210]:
px.line(
    monthly_sales,
    x='Order_Date',
    y='Sales_Amount',
    title='Monthly Sales Trend',
    markers=True).update_traces(line_color='green').show()

In [211]:
df['Order_Date'].max()

Timestamp('2025-12-31 00:00:00')

In [212]:
px.line(
    monthly_sales,
    x='Order_Date',
    y='Sales_Amount',
    title='Monthly Sales Trend',
    markers=True
).update_traces(
    line_color='green'
).update_xaxes(
    range=['2022-01-01', '2025-12-31']
).show()

In [221]:
custome_colors = {
    'Appliances': '#90EE90',
    'Electronics': '#4682B4',
    'Furniture': '#FFA500',
    'Office Supplies': '#FF69B4'
}

px.bar(
    df.groupby('Product_Category', as_index=False)['Sales_Amount'].sum(),
    x='Sales_Amount',
    y='Product_Category',
    orientation='h',
    title='Total Sales by Product Category',
    color='Product_Category',
    color_discrete_map=custome_colors
).update_layout(
    yaxis={'categoryorder': 'total ascending'}
).show()

In [222]:
px.bar(
    df.groupby('Product_Category', as_index=False)['Profit'].sum(),
    x='Profit',
    y='Product_Category',
    orientation='h',
    title='Total Profit by Product Category',
    color='Product_Category',
    color_discrete_map=custome_colors,
    text_auto='.2s'
).update_layout(
    yaxis={'categoryorder': 'total ascending'},
    xaxis_title='Total Profit',
    yaxis_title='Product Category'
).show()

In [242]:
sales_channel = (
    df.groupby('Sales_Channel', as_index=False)['Sales_Amount']
    .sum()
)

channel_colors = {
    'Online': '#4682B4',
    'B2B Portal': '#90EE90',
    'Phone Order': '#adff2f',
    'Retail Store': '#ff8c00'
}

px.bar(
    sales_channel,
    x='Sales_Channel',
    y='Sales_Amount',
    title='Total Sales by Sales Channel',
    color='Sales_Channel',
    color_discrete_map=channel_colors,
    text=sales_channel['Sales_Amount'].map(lambda x: f'{x:,.0f}')
).update_layout(
    xaxis_title='Sales Channel',
    yaxis_title='Total Sales',
    yaxis_tickprefix='$',
    yaxis_tickformat=',.0f',
    showlegend=False
).update_traces(
    textposition='outside'
).show()

In [252]:
sales_region = (
    df.groupby('Region', as_index=False)['Sales_Amount']
    .sum()
    .sort_values('Sales_Amount', ascending=True)
)

px.bar(
    sales_region,
    x='Sales_Amount',
    y='Region',
    orientation='h',
    title='Total Sales by Region',
     color_discrete_sequence=['#4682B4'],
    text=sales_region['Sales_Amount'].map(lambda x: f'{x:,.0f}')
).update_layout(
    xaxis_title='Total Sales',
    yaxis_title='Region',
    xaxis_tickprefix='$',
    xaxis_tickformat=',.0f',
    showlegend=False
).update_traces(
    textposition='outside',
    cliponaxis=False
).show()

In [224]:
status_colors = {
    'Completed': '#2E8B57',
    'Shipped': '#4682B4',
    'Returned': '#FFA500',
    'Processing': '#9370DB',
    'Cancelled': '#DC143C'
}

px.bar(
    df['Order_Status'].value_counts().reset_index(),
    x='Order_Status',
    y='count',
    title='Order Status Distribution',
    color='Order_Status',
    color_discrete_map=status_colors,
    text_auto=True
).update_layout(
    xaxis_title='Order Status',
    yaxis_title='Number of Orders'
).show()

In [228]:
return_colors = {
    'Late Delivery': '#990000', 
    'Wrong Item': '#D92D2D', 
    'Damaged': '#F25353', 
    'Other': '#FF8080', 
    'Defective': '#FFAAAA', 
    'Changed Mind': '#FFCACA' 
}

px.bar(
    df[df['Return_Flag'] == 'Yes']['Return_Reason']
    .value_counts()
    .reindex([
        'Late Delivery',
        'Wrong Item',
        'Damaged',
        'Other',
        'Defective',
        'Changed Mind'
    ], fill_value=0)
    .rename_axis('Return_Reason')
    .reset_index(name='count'),
    x='Return_Reason',
    y='count',
    title='Return Reasons Distribution',
    color='Return_Reason',
    color_discrete_map=return_colors,
    text_auto=True
).update_layout(
    xaxis_title='Return Reason',
    yaxis_title='Number of Returns'
).show()

In [240]:
return_rate = (
    df.groupby('Product_Category')
    .agg(
        Total_Orders=('Order_ID', 'nunique'),
        Returned_Orders=('Return_Flag', lambda x: (x == 'Yes').sum())
    )
    .reset_index()
)

return_rate['Return_Rate'] = (
    return_rate['Returned_Orders'] / return_rate['Total_Orders'] * 100
)

return_colors = {
    'Appliances': '#90EE90',
    'Electronics': '#4682B4',
    'Furniture': '#FFA500',
    'Office Supplies': '#FF69B4'
}

px.bar(
    return_rate,
    x='Product_Category',
    y='Return_Rate',
    title='Return Rate by Product Category',
    color='Product_Category',
    color_discrete_map=return_colors,
    text=return_rate['Return_Rate'].map(lambda x: f'{x:.1f}%')
).update_layout(
    xaxis_title='Product Category',
    yaxis_title='Return Rate (%)',
    yaxis_ticksuffix='%',
    showlegend=False
).update_traces(
    textposition='outside'
).show()

In [230]:
shipping_colors = {
    'Standard': '#2E8B57',
    'Next Day': '#4682B4',
    'Express': '#FFA500',
    'Pickup': '#9370DB'
}

px.box(
    df.dropna(subset=['Delivery_Days']),
    x='Shipping_Method',
    y='Delivery_Days',
    color='Shipping_Method',
    color_discrete_map=shipping_colors,
    title='Delivery Time by Shipping Method'
).update_layout(
    xaxis_title='Shipping Method',
    yaxis_title='Delivery Days'
).show()

In [237]:
rating_colors = {
    1: '#D73027', 
    2: '#F46D43',  
    3: '#FDAE61',  
    4: '#A6D96A', 
    5: '#1A9850'   
}

rating_counts = (
    df.dropna(subset=['Customer_Rating'])['Customer_Rating']
    .value_counts()
    .sort_index()
    .reset_index()
)

px.pie(
    rating_counts,
    names='Customer_Rating',
    values='count',
    title='Customer Rating Breakdown',
    hole=0.5,
    color='Customer_Rating',
    color_discrete_map=rating_colors
).show()

In [253]:
profit_margin = (
    df.groupby('Product_Category', as_index=False)
    .agg(
        Total_Sales=('Sales_Amount', 'sum'),
        Total_Profit=('Profit', 'sum')
    )
)

profit_margin['Profit_Margin'] = (
    profit_margin['Total_Profit'] / profit_margin['Total_Sales'] * 100
)

profit_margin = profit_margin.sort_values(
    'Profit_Margin', ascending=False
)

px.bar(
    profit_margin,
    x='Product_Category',
    y='Profit_Margin',
    title='Profit Margin by Product Category',
    color_discrete_sequence=['#4682B4'],
    text=profit_margin['Profit_Margin'].map(lambda x: f'{x:.1f}%')
).update_layout(
    xaxis_title='Product Category',
    yaxis_title='Profit Margin (%)',
    yaxis_ticksuffix='%',
    showlegend=False
).update_traces(
    textposition='outside',
    cliponaxis=False
).show()

In [279]:
df.isna().sum()

Transaction_ID                       0
Order_ID                             0
Customer_ID                          0
Customer_Name                        0
Customer_Age                         0
Customer_Gender                      0
Customer_Segment                     0
Order_Date                           0
Order_Time                           0
Sales_Channel                        0
Store_ID                             0
Store_Name                           0
Country                              0
Region                               0
City                                 0
Product_ID                           0
Product_Name                         0
Product_Category                     0
Product_Subcategory                  0
Quantity                             0
Unit_Price                           0
Discount_Percentage                  0
Sales_Amount                         0
Cost_Amount                          0
Profit                               0
Payment_Method                       0
Order_Status                         0
Shipping_Method                      0
Delivery_Days                      162
Return_Flag                          0
Return_Reason                        0
Sales_Representative                 0
Promotion_Code                       0
Customer_Rating                   3430
Inventory_Level                      0
Order_Year                           0
Expected_Sales_Before_Rounding       0
Sales_Difference                     0
dtype: int64

In [280]:
df = df.drop(columns=[
    'Sales_Difference',
    'Expected_Sales_Before_Rounding'
])

In [281]:
df.columns

Index(['Transaction_ID', 'Order_ID', 'Customer_ID', 'Customer_Name',
       'Customer_Age', 'Customer_Gender', 'Customer_Segment', 'Order_Date',
       'Order_Time', 'Sales_Channel', 'Store_ID', 'Store_Name', 'Country',
       'Region', 'City', 'Product_ID', 'Product_Name', 'Product_Category',
       'Product_Subcategory', 'Quantity', 'Unit_Price', 'Discount_Percentage',
       'Sales_Amount', 'Cost_Amount', 'Profit', 'Payment_Method',
       'Order_Status', 'Shipping_Method', 'Delivery_Days', 'Return_Flag',
       'Return_Reason', 'Sales_Representative', 'Promotion_Code',
       'Customer_Rating', 'Inventory_Level', 'Order_Year'],
      dtype='str')

In [282]:
df.to_csv('cleaned_retail_dataset.csv', index=False)

In [283]:
import os

print(os.getcwd())

C:\Users\Maison\OneDrive\Desktop

In [284]:
import os
os.getcwd()

'C:\\Users\\Maison\\OneDrive\\Desktop'

In [285]:
os.chdir(r'C:\Users\Maison\OneDrive\Desktop')

In [362]:
%%writefile streamlit_basics.py
import pandas as pd
import plotly.express as px
import streamlit as st

st.set_page_config(page_title="Retail Sales Analysis", layout="wide")

st.markdown(
    """
    <h1 style='text-align: center; color: #4682B4;'>
        Retail Sales Analysis
    </h1>
    <p style='text-align: center; font-size: 16px;'>
        An overview of sales, profit and customer trends from 2022–2025
    </p>
    """,
    unsafe_allow_html=True
)
col_left, col_center, col_right = st.columns([1, 6, 1])
with col_center:
    st.image(r'C:\Users\Maison\OneDrive\Desktop\Retail Img.jpg', use_container_width=True)

# cleaned dataset
df = pd.read_csv("cleaned_retail_dataset.csv")

# Prepare dates for the monthly sales chart
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")

page = st.sidebar.radio(
    "Pages",
    ["Page 1: Sales Overview", "Page 2: Product and Customer Analysis"],
    key="page_navigation",
)

st.sidebar.divider()
st.sidebar.subheader("Filters")
st.sidebar.caption("Choose one or more values")

year_options = sorted(df["Order_Year"].dropna().astype(int).unique().tolist())
region_options = sorted(df["Region"].dropna().astype(str).unique().tolist())
category_options = sorted(df["Product_Category"].dropna().astype(str).unique().tolist())
channel_options = sorted(df["Sales_Channel"].dropna().astype(str).unique().tolist())
payment_options = sorted(df["Payment_Method"].dropna().astype(str).unique().tolist())

selected_years = st.sidebar.multiselect(
    "Order Year", options=year_options, default=[], key="filter_year"
)
selected_regions = st.sidebar.multiselect(
    "Region", options=region_options, default=[], key="filter_region"
)
selected_categories = st.sidebar.multiselect(
    "Product Category", options=category_options, default=[], key="filter_category"
)
selected_channels = st.sidebar.multiselect(
    "Sales Channel", options=channel_options, default=[], key="filter_channel"
)
selected_payment_methods = st.sidebar.multiselect(
    "Payment Method", options=payment_options, default=[], key="filter_payment_method"
)
# Apply selected filters to the dataset
filtered_df = df.copy()

if selected_years:
    filtered_df = filtered_df[
        filtered_df["Order_Year"].isin(selected_years)
    ]

if selected_regions:
    filtered_df = filtered_df[
        filtered_df["Region"].astype(str).isin(selected_regions)
    ]

if selected_categories:
    filtered_df = filtered_df[
        filtered_df["Product_Category"].astype(str).isin(selected_categories)
    ]

if selected_channels:
    filtered_df = filtered_df[
        filtered_df["Sales_Channel"].astype(str).isin(selected_channels)
    ]

if selected_payment_methods:
    filtered_df = filtered_df[
        filtered_df["Payment_Method"].astype(str).isin(selected_payment_methods)
    ]

st.sidebar.caption(
    f"Rows matching filters: {len(filtered_df):,} of {len(df):,}"
)
full_df = df          # keep the original if you ever need it
df = filtered_df      # everything below now uses filtered data

# Colours used
category_colors = {
    "Appliances": "#90EE90",
    "Electronics": "#4682B4",
    "Furniture": "#FFA500",
    "Office Supplies": "#FF69B4"
}

status_colors = {
    "Completed": "#2E8B57",
    "Shipped": "#4682B4",
    "Returned": "#FFA500",
    "Processing": "#9370DB",
    "Cancelled": "#DC143C"
}

return_colors = {
    "Late Delivery": "#990000",
    "Wrong Item": "#D92D2D",
    "Damaged": "#F25353",
    "Other": "#FF8080",
    "Defective": "#FFAAAA",
    "Changed Mind": "#FFCACA"
}

shipping_colors = {
    "Standard": "#2E8B57",
    "Next Day": "#4682B4",
    "Express": "#FFA500",
    "Pickup": "#9370DB"
}

rating_colors = {
    1: "#D73027",
    2: "#F46D43",
    3: "#FDAE61",
    4: "#A6D96A",
    5: "#1A9850"
}


# -------------------------
# PAGE 1: SALES OVERVIEW
# -------------------------
if page == "Page 1: Sales Overview":
    st.header("Sales Overview")

    total_sales = df["Sales_Amount"].sum()
    total_profit = df["Profit"].sum()
    total_orders = df["Order_ID"].nunique()
    average_order_value = total_sales / total_orders if total_orders else 0

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Sales", f"${total_sales:,.0f}")
    col2.metric("Total Profit", f"${total_profit:,.0f}")
    col3.metric("Unique Orders", f"{total_orders:,}")
    col4.metric("Average Order Value", f"${average_order_value:,.2f}")
    st.dataframe(df)

    # Orders by Year
    st.subheader("Orders by Year")
    orders_by_year = df["Order_Year"].value_counts().reset_index()
    fig_year = px.bar(
        orders_by_year,
        x="Order_Year",
        y="count",
        title="Orders by Year",
        color_discrete_sequence=["lightblue"]
    )
    fig_year.update_xaxes(dtick=1, tickmode="linear")
    st.plotly_chart(fig_year, use_container_width=True)

   # Monthly Sales Trend
    st.subheader("Monthly Sales Trend")

    # Create a copy so the original dataset remains unchanged
    monthly_df = df.copy()

    # Convert Order_Date to datetime format
    monthly_df["Order_Date"] = pd.to_datetime(
        monthly_df["Order_Date"],
        errors="coerce"
    )

    # Remove rows with invalid dates for this chart
    monthly_df = monthly_df.dropna(subset=["Order_Date"])

    # Group sales by month
    monthly_df["Month"] = monthly_df["Order_Date"].dt.to_period("M")

    monthly_sales = (
        monthly_df.groupby("Month", as_index=False)["Sales_Amount"]
        .sum()
    )

    # Convert monthly periods back to dates
    monthly_sales["Order_Date"] = (
        monthly_sales["Month"].dt.to_timestamp()
    )

    # Chart
    fig_monthly = px.line(
        monthly_sales,
        x="Order_Date",
        y="Sales_Amount",
        title="Monthly Sales Trend",
        markers=True
    ).update_traces(
        line_color="green"
    ).update_xaxes(
        range=["2022-01-01", "2025-12-31"]
    )

    # Display
    st.plotly_chart(fig_monthly, width="stretch")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Sales by Product Category")
        category_sales = df.groupby(
            "Product_Category", as_index=False
        )["Sales_Amount"].sum()

        fig_category_sales = px.bar(
            category_sales,
            x="Sales_Amount",
            y="Product_Category",
            orientation="h",
            title="Total Sales by Product Category",
            color="Product_Category",
            color_discrete_map=category_colors
        ).update_layout(
            yaxis={"categoryorder": "total ascending"}
        )
        st.plotly_chart(fig_category_sales, use_container_width=True)

    with col2:
        st.subheader("Profit by Product Category")
        category_profit = df.groupby(
            "Product_Category", as_index=False
        )["Profit"].sum()

        fig_category_profit = px.bar(
            category_profit,
            x="Profit",
            y="Product_Category",
            orientation="h",
            title="Total Profit by Product Category",
            color="Product_Category",
            color_discrete_map=category_colors,
            text_auto=".2s"
        ).update_layout(
            yaxis={"categoryorder": "total ascending"},
            xaxis_title="Total Profit",
            yaxis_title="Product Category"
        )
        st.plotly_chart(fig_category_profit, use_container_width=True)

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Sales by Sales Channel")
        sales_channel = df.groupby(
            "Sales_Channel", as_index=False
        )["Sales_Amount"].sum()

        channel_colors = {
            "Online": "#4682B4",
            "B2B Portal": "#90EE90",
            "Phone Order": "#ADFF2F",
            "Retail Store": "#FF8C00"
        }

        fig_channel = px.bar(
            sales_channel,
            x="Sales_Channel",
            y="Sales_Amount",
            title="Total Sales by Sales Channel",
            color="Sales_Channel",
            color_discrete_map=channel_colors,
            text=sales_channel["Sales_Amount"].map(lambda x: f"{x:,.0f}")
        ).update_layout(
            xaxis_title="Sales Channel",
            yaxis_title="Total Sales",
            yaxis_tickprefix="$",
            yaxis_tickformat=",.0f",
            showlegend=False
        ).update_traces(
            textposition="outside"
        )
        st.plotly_chart(fig_channel, use_container_width=True)

    with col2:
        st.subheader("Sales by Region")
        sales_region = (
            df.groupby("Region", as_index=False)["Sales_Amount"]
            .sum()
            .sort_values("Sales_Amount", ascending=True)
        )

        fig_region = px.bar(
            sales_region,
            x="Sales_Amount",
            y="Region",
            orientation="h",
            title="Total Sales by Region",
            color_discrete_sequence=["#4682B4"],
            text=sales_region["Sales_Amount"].map(lambda x: f"{x:,.0f}")
        ).update_layout(
            xaxis_title="Total Sales",
            yaxis_title="Region",
            xaxis_tickprefix="$",
            xaxis_tickformat=",.0f",
            showlegend=False
        ).update_traces(
            textposition="outside",
            cliponaxis=False
        )
        st.plotly_chart(fig_region, use_container_width=True)

    # Order Status Distribution
    st.subheader("Order Status Distribution")
    status_counts = df["Order_Status"].value_counts().reset_index()
    fig_status = px.bar(
        status_counts,
        x="Order_Status",
        y="count",
        title="Order Status Distribution",
        color="Order_Status",
        color_discrete_map=status_colors,
        text_auto=True
    ).update_layout(
        xaxis_title="Order Status",
        yaxis_title="Number of Orders"
    )
    st.plotly_chart(fig_status, use_container_width=True)

# -------------------------
# PAGE 2: PRODUCT AND CUSTOMER ANALYSIS
# -------------------------
elif page == "Page 2: Product and Customer Analysis":
    st.header("Product and Customer Analysis")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Return Reasons Distribution")
        return_counts = (
            df[df["Return_Flag"] == "Yes"]["Return_Reason"]
            .value_counts()
            .reindex(
                ["Late Delivery", "Wrong Item", "Damaged", "Other", "Defective", "Changed Mind"],
                fill_value=0
            )
            .rename_axis("Return_Reason")
            .reset_index(name="count")
        )

        fig_returns = px.bar(
            return_counts,
            x="Return_Reason",
            y="count",
            title="Return Reasons Distribution",
            color="Return_Reason",
            color_discrete_map=return_colors,
            text_auto=True
        ).update_layout(
            xaxis_title="Return Reason",
            yaxis_title="Number of Returns"
        )
        st.plotly_chart(fig_returns, use_container_width=True)

    with col2:
        st.subheader("Return Rate by Product Category")
        return_rate = (
            df.groupby("Product_Category")
            .agg(
                Total_Orders=("Order_ID", "nunique"),
                Returned_Orders=("Return_Flag", lambda x: (x == "Yes").sum())
            )
            .reset_index()
        )
        return_rate["Return_Rate"] = (
            return_rate["Returned_Orders"] / return_rate["Total_Orders"] * 100
        )

        fig_return_rate = px.bar(
            return_rate,
            x="Product_Category",
            y="Return_Rate",
            title="Return Rate by Product Category",
            color="Product_Category",
            color_discrete_map=category_colors,
            text=return_rate["Return_Rate"].map(lambda x: f"{x:.1f}%")
        ).update_layout(
            xaxis_title="Product Category",
            yaxis_title="Return Rate (%)",
            yaxis_ticksuffix="%",
            showlegend=False
        ).update_traces(
            textposition="outside"
        )
        st.plotly_chart(fig_return_rate, use_container_width=True)

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Delivery Time by Shipping Method")
        fig_delivery = px.box(
            df.dropna(subset=["Delivery_Days"]),
            x="Shipping_Method",
            y="Delivery_Days",
            color="Shipping_Method",
            color_discrete_map=shipping_colors,
            title="Delivery Time by Shipping Method"
        ).update_layout(
            xaxis_title="Shipping Method",
            yaxis_title="Delivery Days"
        )
        st.plotly_chart(fig_delivery, use_container_width=True)

    with col2:
        st.subheader("Customer Rating Breakdown")
        rating_counts = (
            df.dropna(subset=["Customer_Rating"])["Customer_Rating"]
            .value_counts()
            .sort_index()
            .reset_index()
        )

        fig_ratings = px.pie(
            rating_counts,
            names="Customer_Rating",
            values="count",
            title="Customer Rating Breakdown",
            hole=0.5,
            color="Customer_Rating",
            color_discrete_map=rating_colors
        )
        st.plotly_chart(fig_ratings, use_container_width=True)

    st.subheader("Profit Margin by Product Category")
    profit_margin = (
        df.groupby("Product_Category", as_index=False)
        .agg(
            Total_Sales=("Sales_Amount", "sum"),
            Total_Profit=("Profit", "sum")
        )
    )
    profit_margin["Profit_Margin"] = (
        profit_margin["Total_Profit"] / profit_margin["Total_Sales"] * 100
    )
    profit_margin = profit_margin.sort_values("Profit_Margin", ascending=False)

    fig_margin = px.bar(
        profit_margin,
        x="Product_Category",
        y="Profit_Margin",
        title="Profit Margin by Product Category",
        color_discrete_sequence=["#4682B4"],
        text=profit_margin["Profit_Margin"].map(lambda x: f"{x:.1f}%")
    ).update_layout(
        xaxis_title="Product Category",
        yaxis_title="Profit Margin (%)",
        yaxis_ticksuffix="%",
        showlegend=False
    ).update_traces(
        textposition="outside",
        cliponaxis=False
    )
    st.plotly_chart(fig_margin, use_container_width=True)

Overwriting streamlit_basics.py

In [266]:
! streamlit run streamlit_basic

^C

In [364]:
!pip install pipreqs

Requirement already satisfied: pipreqs in C:\Users\Maison\.conda\envs\notebook-env\Lib\site-packages (0.4.13)
Requirement already satisfied: docopt in C:\Users\Maison\.conda\envs\notebook-env\Lib\site-packages (from pipreqs) (0.6.2)
Requirement already satisfied: yarg in C:\Users\Maison\.conda\envs\notebook-env\Lib\site-packages (from pipreqs) (0.1.10)
Requirement already satisfied: requests in C:\Users\Maison\.conda\envs\notebook-env\Lib\site-packages (from yarg->pipreqs) (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Maison\.conda\envs\notebook-env\Lib\site-packages (from requests->yarg->pipreqs) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Maison\.conda\envs\notebook-env\Lib\site-packages (from requests->yarg->pipreqs) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Maison\.conda\envs\notebook-env\Lib\site-packages (from requests->yarg->pipreqs) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Maison\.conda\envs\notebook-env\Lib\site-packages (from requests->yarg->pipreqs) (2026.7.22)

In [366]:
! pipreqs ./

WARNING: Import named "pandas" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "pandas" was resolved to "pandas:3.1.0" package (https://pypi.org/project/pandas/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
WARNING: Import named "plotly" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "plotly" was resolved to "plotly:7.1.0" package (https://pypi.org/project/plotly/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
INFO: Successfully saved requirements file in ./requirements.txt